# Generated by Django 6.0 on 2026-01-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('numBureau', models.IntegerField(primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=30)),
                ('pays', models.CharField(max_length=20)),
                ('zoneGeo', models.CharField(max_length=30)),
                ('tarifBase', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
