# Generated by Django 6.0.1 on 2026-01-27 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_remove_client_adrmail_client_email'),
        ('manageExpedition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typePaiement', models.CharField(choices=[('total', 'Total'), ('partiel', 'Partiel')], max_length=10)),
                ('datePaiement', models.DateTimeField(auto_now=True)),
                ('soldePaye', models.DecimalField(decimal_places=2, max_digits=7)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='manageExpedition.facture')),
            ],
        ),
    ]
